export const CLASS_META = [
  { key: 'Car', emoji: '🚗', label: 'Cars' },
  { key: 'Tree', emoji: '🌳', label: 'Trees' },
  { key: 'Street Light', emoji: '💡', label: 'Lights' },
  { key: 'Pole', emoji: '🪧', label: 'Poles' },
  { key: 'Building', emoji: '🏢', label: 'Buildings' },
  { key: 'Motorcycle', emoji: '🏍️', label: 'Motos' },
  { key: 'Person', emoji: '🚶', label: 'People' },
  { key: 'Traffic Signal', emoji: '🚦', label: 'Signals' },
  { key: 'Traffic Sign', emoji: '🛑', label: 'Signs' },
  { key: 'Truck', emoji: '🚚', label: 'Trucks' },
  { key: 'Bus', emoji: '🚌', label: 'Buses' },
  { key: 'Bicycle', emoji: '🚲', label: 'Bicycles' },
  { key: 'Train', emoji: '🚆', label: 'Trains' },
  { key: 'Bench', emoji: '🪑', label: 'Benches' },
  { key: 'Fire Hydrant', emoji: '🧯', label: 'Hydrants' },
  { key: 'Potted Plant', emoji: '🪴', label: 'Plants' },
  { key: 'Dustbin', emoji: '🗑️', label: 'Dustbins' },
  { key: 'Bollards', emoji: '🔶', label: 'Bollards' },
  { key: 'Garbage Container', emoji: '♻️', label: 'Garbage' },
  { key: 'Stairs', emoji: '🪜', label: 'Stairs' },
  { key: 'Street Railing', emoji: '🚧', label: 'Railings' },
]

export const CLASS_COLORS = {
  Car: '#FF7800',
  Tree: '#50C800',
  'Street Light': '#00DCF0',
  Pole: '#FF50C8',
  Building: '#3264FF',
  Motorcycle: '#FFC832',
  Person: '#6432FF',
  'Traffic Signal': '#00FFC8',
  'Traffic Sign': '#00B4FF',
  Truck: '#3264C8',
  Bus: '#2850B4',
  Bicycle: '#64C864',
  Train: '#7886B4',
  Bench: '#8C6450',
  'Fire Hydrant': '#0064FF',
  'Potted Plant': '#3CB43C',
  Dustbin: '#646464',
  Bollards: '#B4B450',
  'Garbage Container': '#5A5A8C',
  Stairs: '#A08C78',
  'Street Railing': '#C8A08C',
}

export const CLASS_EMOJIS = {
  Car: '🚗',
  Tree: '🌳',
  'Street Light': '💡',
  Pole: '🪧',
  Building: '🏢',
  Motorcycle: '🏍️',
  Person: '🚶',
  'Traffic Signal': '🚦',
  'Traffic Sign': '🛑',
  Truck: '🚚',
  Bus: '🚌',
  Bicycle: '🚲',
  Train: '🚆',
  Bench: '🪑',
  'Fire Hydrant': '🧯',
  'Potted Plant': '🪴',
  Dustbin: '🗑️',
  Bollards: '🔶',
  'Garbage Container': '♻️',
  Stairs: '🪜',
  'Street Railing': '🚧',
}
